In [1]:
from fuzzywuzzy import fuzz
import numpy as np
import pandas as pd

c:\Users\lenym\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
df = pd.DataFrame({
    "nama": ["Suyatno", "Ayu Prahara", "Prahara Ayu", "P. Ayu", "P. Ayu","Sandra Dewi", "Dew Sandra", "Pramita Adin", "P. Adin", "Niko", "nico"],
    "ibu_kandung":["Bunga", "Diva Pertiwi", "Pertiwi Diva","P. Diva", "Dita", "Lina Sandra", "Sandra Lina", "Amelia Assyfa", "Assyfa A", "Roselina Sulina", "Mawar Sri"],
    "alamat":["Tanah Abang", "Blok m", "Blok m", "m Block", "Block m", "Antapani", "Antapani", "Ciputra", "Ciputra", "Ciputra", "bSD"],
    "dob":["1970/01/01", "1985/12/05", "1985/12/05", "1985/12/05", "1999/04/18", "1989/03/15", "1989/03/15", "2000/09/20", "2000/09/20", "1992/02/02", "1998/10/19"],
    })
df

nama      ibu_kandung       alamat         dob
0        Suyatno            Bunga  Tanah Abang  1970/01/01
1    Ayu Prahara     Diva Pertiwi       Blok m  1985/12/05
2    Prahara Ayu     Pertiwi Diva       Blok m  1985/12/05
3         P. Ayu          P. Diva      m Block  1985/12/05
4         P. Ayu             Dita      Block m  1999/04/18
5    Sandra Dewi      Lina Sandra     Antapani  1989/03/15
6     Dew Sandra      Sandra Lina     Antapani  1989/03/15
7   Pramita Adin    Amelia Assyfa      Ciputra  2000/09/20
8        P. Adin         Assyfa A      Ciputra  2000/09/20
9           Niko  Roselina Sulina      Ciputra  1992/02/02
10          nico        Mawar Sri          bSD  1998/10/19

In [3]:
df.sort_values(["dob"])

nama      ibu_kandung       alamat         dob
0        Suyatno            Bunga  Tanah Abang  1970/01/01
1    Ayu Prahara     Diva Pertiwi       Blok m  1985/12/05
2    Prahara Ayu     Pertiwi Diva       Blok m  1985/12/05
3         P. Ayu          P. Diva      m Block  1985/12/05
5    Sandra Dewi      Lina Sandra     Antapani  1989/03/15
6     Dew Sandra      Sandra Lina     Antapani  1989/03/15
9           Niko  Roselina Sulina      Ciputra  1992/02/02
10          nico        Mawar Sri          bSD  1998/10/19
4         P. Ayu             Dita      Block m  1999/04/18
7   Pramita Adin    Amelia Assyfa      Ciputra  2000/09/20
8        P. Adin         Assyfa A      Ciputra  2000/09/20

In [4]:
nama = np.char.lower(list(df["nama"]))
ibu_kandung = np.char.lower(list(df["ibu_kandung"]))
alamat = np.char.lower(list(df["alamat"]))
dob = np.char.lower(list(df["dob"]))
dob

array(['1970/01/01', '1985/12/05', '1985/12/05', '1985/12/05',
       '1999/04/18', '1989/03/15', '1989/03/15', '2000/09/20',
       '2000/09/20', '1992/02/02', '1998/10/19'], dtype='<U10')

In [5]:
ibu_kandung

array(['bunga', 'diva pertiwi', 'pertiwi diva', 'p. diva', 'dita',
       'lina sandra', 'sandra lina', 'amelia assyfa', 'assyfa a',
       'roselina sulina', 'mawar sri'], dtype='<U15')

In [6]:
dob

array(['1970/01/01', '1985/12/05', '1985/12/05', '1985/12/05',
       '1999/04/18', '1989/03/15', '1989/03/15', '2000/09/20',
       '2000/09/20', '1992/02/02', '1998/10/19'], dtype='<U10')

In [7]:
dob_baru = np.array([])
for i in range(len(dob)):
    dob_baru = np.append(dob_baru, dob[i][2:].replace("/",""))
dob = dob_baru

In [36]:
hasil = []
for i in range(len(nama)):
    # sementara = np.array([])
    for j in range(len(nama)):
        score = 0
        score_nama = fuzz.ratio(nama[i], nama[j])
        score_nama_2 = fuzz.token_sort_ratio(nama[i], nama[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_nama_2> score_nama:
            score_nama = score_nama_2

        score_ibu = fuzz.ratio(ibu_kandung[i], ibu_kandung[j])
        score_ibu_2 = fuzz.token_sort_ratio(ibu_kandung[i], ibu_kandung[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_ibu_2> score_ibu:
            score_ibu = score_ibu_2

        score_alamat = fuzz.ratio(alamat[i],alamat[j])
        score_alamat_2 = fuzz.token_sort_ratio(alamat[i],alamat[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_alamat_2>score_alamat:
            score_alamat = score_alamat_2

        score_dob = fuzz.ratio(dob[i],dob[j])

        score = score_nama*0.5 + score_ibu*0.3 + score_alamat*0.1 + score_dob*0.1
        # score = score_nama + score_ibu
        if score_nama <= 20: # batas bawah seseorang dianggap memiliki nama yang sama
            score = 0
        if score_ibu <= 20: # batas bawah seseorang dianggap memiliki nama ibu yang sama
            score = 0
        if score_nama >60 and score_ibu <= 60 and score_dob <= 30:
            score = 0
        hasil = np.append(
            hasil,
            nama[i]+" dan "+nama[j]+" : "+
            "\n score nama : "+str(score_nama)+" ("+nama[i]+" & "+nama[j]+")"+
            "\n score ibu : "+str(score_ibu)+" ("+ibu_kandung[i]+" & "+ibu_kandung[j]+")"+
            "\n score alamat : "+str(score_alamat)+" ("+alamat[i]+" & "+alamat[j]+")"+
            "\n score dob : "+str(score_dob)+" ("+dob[i]+" & "+dob[j]+")"+
            "\n score total : "+str(score)
            )
        # sementara = np.append(sementara, score)
    # hasil.append(sementara)



In [39]:
hasil = []
for i in range(len(nama)):
    sementara = np.array([])
    for j in range(len(nama)):
        score = 0

        score_nama = fuzz.ratio(nama[i], nama[j])
        score_nama_2 = fuzz.token_sort_ratio(nama[i], nama[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_nama_2> score_nama:
            score_nama = score_nama_2

        score_ibu = fuzz.ratio(ibu_kandung[i], ibu_kandung[j])
        score_ibu_2 = fuzz.token_sort_ratio(ibu_kandung[i], ibu_kandung[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_ibu_2> score_ibu:
            score_ibu = score_ibu_2

        score_alamat = fuzz.ratio(alamat[i],alamat[j])
        score_alamat_2 = fuzz.token_sort_ratio(alamat[i],alamat[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_alamat_2>score_alamat:
            score_alamat = score_alamat_2

        score_dob = fuzz.ratio(dob[i],dob[j])

        score = score_nama*0.5 + score_ibu*0.3 + score_alamat*0.1 + score_dob*0.1
        if score_nama <= 20: # batas bawah seseorang dianggap memiliki nama yang sama
            score = 0
        if score_ibu <= 20: # batas bawah seseorang dianggap memiliki nama ibu yang sama
            score = 0
        if score_nama >60 and score_ibu <= 60 and score_dob <= 30:
            score = 0
        sementara = np.append(sementara, score)
    hasil.append(sementara)

In [40]:
for i in range(len(hasil)):
    print(hasil[i])

[100.    0.    0.    0.    0.   32.6  33.6   0.    0.   32.5   0. ]
[  0.  100.  100.   70.3   0.   27.3  28.3  36.5   0.    0.    0. ]
[  0.  100.  100.   70.3   0.   31.8  28.3  38.9   0.    0.    0. ]
[  0.   70.3  70.3 100.    0.    0.   26.3  31.8  44.4   0.    0. ]
[  0.    0.    0.    0.  100.    0.   29.5  29.4   0.    0.    0. ]
[ 32.6  29.   33.5   0.    0.  100.   97.5  41.1  34.7  34.3  28.8]
[ 33.6  30.   30.   28.   25.6  97.5 100.   37.6  29.7   0.    0. ]
[  0.   36.5  36.5  31.8   0.   35.5  36.  100.   76.3   0.    0. ]
[  0.    0.    0.   44.4   0.   32.1  33.1  76.3 100.    0.    0. ]
[  0.    0.    0.    0.    0.   36.7   0.   42.5   0.  100.   50.7]
[  0.    0.    0.    0.    0.   28.8   0.   26.6   0.   50.7 100. ]


In [41]:
hasil

[array([100. ,   0. ,   0. ,   0. ,   0. ,  32.6,  33.6,   0. ,   0. ,
         32.5,   0. ]),
 array([  0. , 100. , 100. ,  70.3,   0. ,  27.3,  28.3,  36.5,   0. ,
          0. ,   0. ]),
 array([  0. , 100. , 100. ,  70.3,   0. ,  31.8,  28.3,  38.9,   0. ,
          0. ,   0. ]),
 array([  0. ,  70.3,  70.3, 100. ,   0. ,   0. ,  26.3,  31.8,  44.4,
          0. ,   0. ]),
 array([  0. ,   0. ,   0. ,   0. , 100. ,   0. ,  29.5,  29.4,   0. ,
          0. ,   0. ]),
 array([ 32.6,  29. ,  33.5,   0. ,   0. , 100. ,  97.5,  41.1,  34.7,
         34.3,  28.8]),
 array([ 33.6,  30. ,  30. ,  28. ,  25.6,  97.5, 100. ,  37.6,  29.7,
          0. ,   0. ]),
 array([  0. ,  36.5,  36.5,  31.8,   0. ,  35.5,  36. , 100. ,  76.3,
          0. ,   0. ]),
 array([  0. ,   0. ,   0. ,  44.4,   0. ,  32.1,  33.1,  76.3, 100. ,
          0. ,   0. ]),
 array([  0. ,   0. ,   0. ,   0. ,   0. ,  36.7,   0. ,  42.5,   0. ,
        100. ,  50.7]),
 array([  0. ,   0. ,   0. ,   0. ,   0. ,  28.8, 

In [ ]:
data = {}
nama_edit = []
for i in range(len(nama)):
    nomor = 1
    name = nama[i]
    while name in nama_edit:
        nomor+=1
        name = name+"("+str(nomor)+")"
    nama_edit.append(name)

In [42]:
# hanya visualisasi saja agar membantu mengingat flownya
data = {}
for i in range(len(nama_edit)):
    data[nama_edit[i]] = hasil[i]
df_hasil = pd.DataFrame(data,index=nama_edit)
df_hasil

suyatno  ayu prahara  prahara ayu  p. ayu  p. ayu(2)  \
suyatno         100.0          0.0          0.0     0.0        0.0   
ayu prahara       0.0        100.0        100.0    70.3        0.0   
prahara ayu       0.0        100.0        100.0    70.3        0.0   
p. ayu            0.0         70.3         70.3   100.0        0.0   
p. ayu(2)         0.0          0.0          0.0     0.0      100.0   
sandra dewi      32.6         27.3         31.8     0.0        0.0   
dew sandra       33.6         28.3         28.3    26.3       29.5   
pramita adin      0.0         36.5         38.9    31.8       29.4   
p. adin           0.0          0.0          0.0    44.4        0.0   
niko             32.5          0.0          0.0     0.0        0.0   
nico              0.0          0.0          0.0     0.0        0.0   

              sandra dewi  dew sandra  pramita adin  p. adin   niko   nico  
suyatno              32.6        33.6           0.0      0.0    0.0    0.0  
ayu prahara          29.0        30.0          36.5      0.0    0.0    0.0  
prahara ayu          33.5        30.0          36.5      0.0    0.0    0.0  
p. ayu                0.0        28.0          31.8     44.4    0.0    0.0  
p. ayu(2)             0.0        25.6           0.0      0.0    0.0    0.0  
sandra dewi         100.0        97.5          35.5     32.1   36.7   28.8  
dew sandra           97.5       100.0          36.0     33.1    0.0    0.0  
pramita adin         41.1        37.6         100.0     76.3   42.5   26.6  
p. adin              34.7        29.7          76.3    100.0    0.0    0.0  
niko                 34.3         0.0           0.0      0.0  100.0   50.7  
nico                 28.8         0.0           0.0      0.0   50.7  100.0

In [50]:
list_nama_sama = []
for i in range(len(hasil)):
    sementara = np.array([])
    for j in range(len(hasil[i])):
        if i != j:
            if hasil[i][j] >60:
                sementara= np.append(sementara,nama_edit[j])
    list_nama_sama.append(sementara)

In [44]:
list_nama_sama

[array([], dtype=float64),
 array(['prahara ayu', 'p. ayu'], dtype='<U32'),
 array(['ayu prahara', 'p. ayu'], dtype='<U32'),
 array(['ayu prahara', 'prahara ayu'], dtype='<U32'),
 array([], dtype=float64),
 array(['dew sandra'], dtype='<U32'),
 array(['sandra dewi'], dtype='<U32'),
 array(['p. adin'], dtype='<U32'),
 array(['pramita adin'], dtype='<U32'),
 array([], dtype=float64),
 array([], dtype=float64)]

In [51]:
df_final = pd.DataFrame({"orang sama":list_nama_sama}, index=nama_edit)
df_final

orang sama
suyatno                               []
ayu prahara        [prahara ayu, p. ayu]
prahara ayu        [ayu prahara, p. ayu]
p. ayu        [ayu prahara, prahara ayu]
p. ayu(2)                             []
sandra dewi                 [dew sandra]
dew sandra                 [sandra dewi]
pramita adin                   [p. adin]
p. adin                   [pramita adin]
niko                                  []
nico                                  []

#### harus nanya ke pak robby apakah jika ada perubahan alamat ada flagnya atau tidak
#### tanya pak robby apa mungkin ada kejadian kesalahan pengetikan NIK (untuk apa memeriksa fuzzy jika data NIK sudah pasti benar/unik)

In [56]:
df_final.to_dict().pop("orang sama")

{'suyatno': array([], dtype=float64),
 'ayu prahara': array(['prahara ayu', 'p. ayu'], dtype='<U32'),
 'prahara ayu': array(['ayu prahara', 'p. ayu'], dtype='<U32'),
 'p. ayu': array(['ayu prahara', 'prahara ayu'], dtype='<U32'),
 'p. ayu(2)': array([], dtype=float64),
 'sandra dewi': array(['dew sandra'], dtype='<U32'),
 'dew sandra': array(['sandra dewi'], dtype='<U32'),
 'pramita adin': array(['p. adin'], dtype='<U32'),
 'p. adin': array(['pramita adin'], dtype='<U32'),
 'niko': array([], dtype=float64),
 'nico': array([], dtype=float64)}

In [62]:
len(df_final.to_dict()["orang sama"])

11