In [1]:
from fuzzywuzzy import fuzz
import numpy as np
import pandas as pd

c:\Users\lenym\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [53]:
df = pd.DataFrame({
    "nama": ["Suyatno", "Ayu Prahara", "Prahara Ayu", "P. Ayu", "P. Ayu","Sandra Dewi", "Dew Sandra", "Pramita Adin", "P. Adin", "Niko", "nico"],
    "ibu_kandung":["Bunga", "Diva Pertiwi", "Pertiwi Diva","P. Diva", "Dita", "Lina Sandra", "Sandra Lina", "Amelia Assyfa", "Assyfa A", "Roselina Sulina", "Mawar Sri"],
    # "alamat":["Tanah Abang", "Blok m", "Blok m", "m Block", "Block m", "Antapani", "Antapani", "Ciputra", "Ciputra", "Ciputra", "bSD"],
    "dob":[],
    "nik":[]
    # "pekerjaan":[""]
    })
df

nama      ibu_kandung
0        Suyatno            Bunga
1    Ayu Prahara     Diva Pertiwi
2    Prahara Ayu     Pertiwi Diva
3         P. Ayu          P. Diva
4         P. Ayu             Dita
5    Sandra Dewi      Lina Sandra
6     Dew Sandra      Sandra Lina
7   Pramita Adin    Amelia Assyfa
8        P. Adin         Assyfa A
9           Niko  Roselina Sulina
10          nico        Mawar Sri

In [60]:
nama = np.char.lower(list(df["nama"]))
ibu_kandung = np.char.lower(list(df["ibu_kandung"]))
# alamat = np.char.lower(list(df["alamat"]))
nama

array(['suyatno', 'ayu prahara', 'prahara ayu', 'p. ayu', 'p. ayu',
       'sandra dewi', 'dew sandra', 'pramita adin', 'p. adin', 'niko',
       'nico'], dtype='<U12')

In [61]:
ibu_kandung

array(['bunga', 'diva pertiwi', 'pertiwi diva', 'p. diva', 'dita',
       'lina sandra', 'sandra lina', 'amelia assyfa', 'assyfa a',
       'roselina sulina', 'mawar sri'], dtype='<U15')

In [71]:
hasil = []
for i in range(len(nama)):
    sementara = np.array([])
    for j in range(len(nama)):
        score = 0
        score_nama = fuzz.ratio(nama[i], nama[j])
        score_nama_2 = fuzz.token_sort_ratio(nama[i], nama[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_nama_2> score_nama:
            score_nama = score_nama_2
        score_ibu = fuzz.ratio(ibu_kandung[i], ibu_kandung[j])
        score_ibu_2 = fuzz.token_sort_ratio(ibu_kandung[i], ibu_kandung[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        if score_ibu_2> score_ibu:
            score_ibu = score_ibu_2
        # score_alamat = fuzz.ratio(alamat[i],alamat[j])
        # score_alamat_2 = fuzz.token_sort_ratio(alamat[i],alamat[j]) # split perkata sebelum diperiksa ratio menggunakan levenshtein
        # if score_alamat_2>score_alamat:
        #     score_alamat = score_alamat_2
        # score = score_nama + score_ibu + score_alamat
        score = score_nama + score_ibu
        if score_nama <= 20: # batas bawah seseorang dianggap memiliki nama yang sama
            score = 0
        if score_ibu <= 20: # batas bawah seseorang dianggap memiliki nama ibu yang sama
            score = 0
        # hasil = np.append(
        #     hasil,
        #     nama[i]+" dan "+nama[j]+" : "+
        #     "\n score nama : "+str(score_nama)+" ("+nama[i]+" & "+nama[j]+")"+
        #     "\n score ibu : "+str(score_ibu)+" ("+ibu_kandung[i]+" & "+ibu_kandung[j]+")"+
        #     # "\n score alamat : "+str(score_alamat)+" ("+alamat[i]+" & "+alamat[j]+")"+
        #     "\n score total : "+str(score)
        #     )
        sementara = np.append(sementara, score)
    hasil.append(sementara)



In [72]:
for i in range(len(hasil)):
    print(hasil[i])

[200.   0.   0.   0.   0.  58.  60.   0.   0.  66.   0.]
[  0. 200. 200. 129. 100.  62.  64.  76.   0.   0.   0.]
[  0. 200. 200. 129. 100.  71.  64.  84.   0.   0.   0.]
[  0. 129. 129. 200. 160.   0.  60.  67.  91.   0.   0.]
[  0. 100. 100. 160. 200.   0.  65.  59.   0.   0.   0.]
[ 58.  62.  71.   0.   0. 200. 195.  93.  77.  81.  67.]
[ 60.  64.  64.  60.  52. 195. 200.  86.  67.   0.   0.]
[  0.  76.  76.  67.   0.  85.  86. 200. 143.   0.   0.]
[  0.   0.   0.  91.   0.  75.  77. 143. 200.   0.   0.]
[  0.   0.   0.   0.   0.  89.   0.  75.   0. 200. 108.]
[  0.   0.   0.   0.   0.  67.   0.  61.   0. 108. 200.]


In [73]:
hasil

[array([200.,   0.,   0.,   0.,   0.,  58.,  60.,   0.,   0.,  66.,   0.]),
 array([  0., 200., 200., 129., 100.,  62.,  64.,  76.,   0.,   0.,   0.]),
 array([  0., 200., 200., 129., 100.,  71.,  64.,  84.,   0.,   0.,   0.]),
 array([  0., 129., 129., 200., 160.,   0.,  60.,  67.,  91.,   0.,   0.]),
 array([  0., 100., 100., 160., 200.,   0.,  65.,  59.,   0.,   0.,   0.]),
 array([ 58.,  62.,  71.,   0.,   0., 200., 195.,  93.,  77.,  81.,  67.]),
 array([ 60.,  64.,  64.,  60.,  52., 195., 200.,  86.,  67.,   0.,   0.]),
 array([  0.,  76.,  76.,  67.,   0.,  85.,  86., 200., 143.,   0.,   0.]),
 array([  0.,   0.,   0.,  91.,   0.,  75.,  77., 143., 200.,   0.,   0.]),
 array([  0.,   0.,   0.,   0.,   0.,  89.,   0.,  75.,   0., 200., 108.]),
 array([  0.,   0.,   0.,   0.,   0.,  67.,   0.,  61.,   0., 108., 200.])]

In [77]:
# hanya visualisasi saja agar membantu mengingat flownya
data = {}
for i in range(len(nama)):
    data[nama[i]] = hasil[i]
df_hasil = pd.DataFrame(data,index=nama)
df_hasil

suyatno  ayu prahara  prahara ayu  p. ayu  sandra dewi  \
suyatno         200.0          0.0          0.0     0.0         58.0   
ayu prahara       0.0        200.0        200.0   100.0         62.0   
prahara ayu       0.0        200.0        200.0   100.0         71.0   
p. ayu            0.0        129.0        129.0   160.0          0.0   
p. ayu            0.0        100.0        100.0   200.0          0.0   
sandra dewi      58.0         62.0         71.0     0.0        200.0   
dew sandra       60.0         64.0         64.0    65.0        195.0   
pramita adin      0.0         76.0         84.0    59.0         93.0   
p. adin           0.0          0.0          0.0     0.0         77.0   
niko             66.0          0.0          0.0     0.0         81.0   
nico              0.0          0.0          0.0     0.0         67.0   

              dew sandra  pramita adin  p. adin   niko   nico  
suyatno             60.0           0.0      0.0    0.0    0.0  
ayu prahara         64.0          76.0      0.0    0.0    0.0  
prahara ayu         64.0          76.0      0.0    0.0    0.0  
p. ayu              60.0          67.0     91.0    0.0    0.0  
p. ayu              52.0           0.0      0.0    0.0    0.0  
sandra dewi        195.0          85.0     75.0   89.0   67.0  
dew sandra         200.0          86.0     77.0    0.0    0.0  
pramita adin        86.0         200.0    143.0   75.0   61.0  
p. adin             67.0         143.0    200.0    0.0    0.0  
niko                 0.0           0.0      0.0  200.0  108.0  
nico                 0.0           0.0      0.0  108.0  200.0

In [79]:
list_nama_sama = []
for i in range(len(hasil)):
    sementara = np.array([])
    for j in range(len(hasil[i])):
        if i != j:
            if hasil[i][j] >=120:
                sementara= np.append(sementara,nama[j])
    list_nama_sama.append(sementara)

In [80]:
list_nama_sama

[array([], dtype=float64),
 array(['prahara ayu', 'p. ayu'], dtype='<U32'),
 array(['ayu prahara', 'p. ayu'], dtype='<U32'),
 array(['ayu prahara', 'prahara ayu', 'p. ayu'], dtype='<U32'),
 array(['p. ayu'], dtype='<U32'),
 array(['dew sandra'], dtype='<U32'),
 array(['sandra dewi'], dtype='<U32'),
 array(['p. adin'], dtype='<U32'),
 array(['pramita adin'], dtype='<U32'),
 array([], dtype=float64),
 array([], dtype=float64)]

In [84]:
df_final = pd.DataFrame({"orang sama":list_nama_sama}, index=nama)
df_final

orang sama
suyatno                                       []
ayu prahara                [prahara ayu, p. ayu]
prahara ayu                [ayu prahara, p. ayu]
p. ayu        [ayu prahara, prahara ayu, p. ayu]
p. ayu                                  [p. ayu]
sandra dewi                         [dew sandra]
dew sandra                         [sandra dewi]
pramita adin                           [p. adin]
p. adin                           [pramita adin]
niko                                          []
nico                                          []

#### harus nanya ke pak robby apakah jika ada perubahan alamat ada flagnya atau tidak
#### tanya pak robby apa mungkin ada kejadian kesalahan pengetikan NIK (untuk apa memeriksa fuzzy jika data NIK sudah pasti benar/unik)